import type { ImageAsset } from "./types";

export const heroImage = {
  id: "hero-202309",
  src: "/images/hero/202309 - 4x6.jpg",
  mobileSrc: "/images/hero/202309 - 4x6.jpg",
  alt: "The couple together outdoors in a romantic scenic setting",
  caption: "The day we have been waiting for",
  width: 2555,
  height: 1703,
  blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
  slot: "hero",
  aspectRatio: 16 / 9,
  role: "hero",
  status: "approved",
  sourcePath: "/images/hero/202309 - 4x6.jpg",
} satisfies ImageAsset;

export const storyImages = [
  {
    id: "story-college-visits",
    src: "/images/story/color-run.webp",
    mobileSrc: "/images/story/color-run.webp",
    alt: "The couple smiling after a colorful fun run",
    caption: "Running, laughing, and arriving home covered in color.",
    width: 1170,
    height: 1455,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1170 / 1455,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/color-run.webp",
  },
  {
    id: "story-first-home",
    src: "/images/story/first-home-christmas.webp",
    mobileSrc: "/images/story/first-home-christmas.webp",
    alt: "The couple holding their dog in front of a Christmas tree at home",
    caption: "A Christmas at home together with Lenny.",
    width: 1536,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 3 / 4,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/first-home-christmas.webp",
  },
  {
    id: "story-raising-lenny",
    src: "/images/story/raising-lenny.webp",
    mobileSrc: "/images/story/raising-lenny.webp",
    alt: "The couple cuddling Lenny together on the grass",
    caption: "A happy day outside with Lenny.",
    width: 800,
    height: 1732,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 800 / 1732,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/raising-lenny.webp",
  },
  {
    id: "story-highschool-graduation",
    src: "/images/story/highschool-graduation.webp",
    mobileSrc: "/images/story/highschool-graduation.webp",
    alt: "A photograph from a high school graduation celebration",
    caption: "Celebrating the people we were becoming, side by side.",
    width: 480,
    height: 319,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyLandscape",
    aspectRatio: 3 / 2,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/highschool-graduation.webp",
  },
  {
    id: "story-traveling-the-world",
    src: "/images/story/traveling-the-world.webp",
    mobileSrc: "/images/story/traveling-the-world.webp",
    alt: "A photograph from the couple's travels around the world",
    caption: "The world got bigger, and so did our story.",
    width: 3024,
    height: 4032,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 3 / 4,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/traveling-the-world.webp",
  },
  {
    id: "story-traditional-portrait",
    src: "/images/story/traditional-portrait.webp",
    mobileSrc: "/images/story/traditional-portrait.webp",
    alt: "The couple smiling together in traditional red wedding attire",
    caption: "A joyful portrait in traditional wedding attire.",
    width: 1365,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1365 / 2048,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/traditional-portrait.webp",
  },
  {
    id: "story-garden-gate",
    src: "/images/story/garden-gate.webp",
    mobileSrc: "/images/story/garden-gate.webp",
    alt: "The couple walking together through a traditional Chinese garden gate",
    caption: "A quiet walk through a place rich with history.",
    width: 1365,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1365 / 2048,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/garden-gate.webp",
  },
  {
    id: "story-red-ceremony",
    src: "/images/story/red-ceremony.webp",
    mobileSrc: "/images/story/red-ceremony.webp",
    alt: "The couple sharing a playful moment in red traditional wedding clothes",
    caption: "A playful moment full of color and joy.",
    width: 1365,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1365 / 2048,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/red-ceremony.webp",
  },
  {
    id: "story-courtyard-wedding",
    src: "/images/story/courtyard-wedding.webp",
    mobileSrc: "/images/story/courtyard-wedding.webp",
    alt: "The couple walking together in wedding attire along a garden corridor",
    caption: "Walking together into a new chapter.",
    width: 1365,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1365 / 2048,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/courtyard-wedding.webp",
  },
  {
    id: "story-prom-rose",
    src: "/images/story/prom-rose.webp",
    mobileSrc: "/images/story/prom-rose.webp",
    alt: "The couple dressed up together, holding a pink rose",
    caption: "One of the early memories that started it all.",
    width: 1536,
    height: 2048,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1536 / 2048,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/prom-rose.webp",
  },
  {
    id: "story-kayaking",
    src: "/images/story/kayaking.webp",
    mobileSrc: "/images/story/kayaking.webp",
    alt: "The couple kayaking together on a lake",
    caption: "Exploring the lake together, one paddle at a time.",
    width: 1170,
    height: 1306,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1170 / 1306,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/kayaking.webp",
  },
  {
    id: "story-color-run",
    src: "/images/story/color-run.webp",
    mobileSrc: "/images/story/color-run.webp",
    alt: "The couple smiling after a colorful fun run",
    caption: "Running, laughing, and arriving home covered in color.",
    width: 1170,
    height: 1455,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1170 / 1455,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/color-run.webp",
  },
  {
    id: "story-school-hallway",
    src: "/images/story/school-hallway.webp",
    mobileSrc: "/images/story/school-hallway.webp",
    alt: "The couple walking hand in hand down a school hallway",
    caption: "Side by side, with plenty of life still ahead.",
    width: 1170,
    height: 1166,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyLandscape",
    aspectRatio: 1170 / 1166,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/school-hallway.webp",
  },
  {
    id: "story-beach-proposal",
    src: "/images/story/beach-proposal.webp",
    mobileSrc: "/images/story/beach-proposal.webp",
    alt: "The couple together on a beach beside a lit marriage proposal display",
    caption: "A beachside question, answered with a joyful yes.",
    width: 1535,
    height: 1965,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1535 / 1965,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/beach-proposal.webp",
  },
] satisfies ImageAsset[];
