import type { ImageAsset } from "./types";

export const heroImage = {
  id: "hero-202309",
  src: "/images/hero/202309 - 4x6.jpg",
  mobileSrc: "/images/hero/202309 - 4x6.jpg",
  alt: "The couple together outdoors in a romantic scenic setting",
  caption: "The day we have been waiting for",
  width: 2555,
  height: 1703,
  blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
  slot: "hero",
  aspectRatio: 16 / 9,
  role: "hero",
  status: "approved",
  sourcePath: "/images/hero/202309 - 4x6.jpg",
} satisfies ImageAsset;

export const storyImages = [
  {
    id: "story-college-visits",
    src: "/images/story/college-visits.webp",
    mobileSrc: "/images/story/college-visits.webp",
    alt: "A photograph from one of the couple's college visits",
    caption: "",
    width: 197,
    height: 197,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 1,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/college-visits.webp",
  },
  {
    id: "story-first-home",
    src: "/images/story/first-home.webp",
    mobileSrc: "/images/story/first-home.webp",
    alt: "A photograph from the couple's first home",
    caption: "Our first home, and the beginning of so many shared routines.",
    width: 4032,
    height: 3024,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyLandscape",
    aspectRatio: 4 / 3,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/first-home.webp",
  },
  {
    id: "story-highschool-graduation",
    src: "/images/story/highschool-graduation.webp",
    mobileSrc: "/images/story/highschool-graduation.webp",
    alt: "A photograph from a high school graduation celebration",
    caption: "Celebrating the people we were becoming, side by side.",
    width: 480,
    height: 319,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyLandscape",
    aspectRatio: 3 / 2,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/highschool-graduation.webp",
  },
  {
    id: "story-traveling-the-world",
    src: "/images/story/traveling-the-world.webp",
    mobileSrc: "/images/story/traveling-the-world.webp",
    alt: "A photograph from the couple's travels around the world",
    caption: "The world got bigger, and so did our story.",
    width: 3024,
    height: 4032,
    blurDataURL: "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",
    slot: "storyPortrait",
    aspectRatio: 3 / 4,
    role: "story",
    status: "approved",
    sourcePath: "/images/story/traveling-the-world.webp",
  },
] satisfies ImageAsset[];
