import type { StoryMoment } from "./types";

export const storyMoments = [
    {
    id: "highschool-graduation",
    heading: "Growing together",
    body: "We have cheered each other through every new beginning and every leap into what comes next.",
    imageId: "story-highschool-graduation",
    imageSlot: "storyLandscape",
    alt: "A photograph from a high school graduation celebration",
    caption: "Celebrating the people we were becoming, side by side.",
    order: 1,
  },
  {
    id: "college-visits",
    heading: "The early chapters",
    body: "During long distance in college, there were the vists that made being together feel extra special.",
    imageId: "story-college-visits",
    imageSlot: "storyPortrait",
    alt: "A photograph from one of the couple's college visits",
    caption: "The first places we learned to make memories together.",
    order: 2,
  },
    {
    id: "traveling-the-world",
    heading: "Out into the world",
    body: "Every journey has given us another story to bring home and another reason to keep exploring.",
    imageId: "story-traveling-the-world",
    imageSlot: "storyPortrait",
    alt: "A photograph from the couple's travels around the world",
    caption: "The world got bigger, and so did our story.",
    order: 3,
  },
  {
    id: "first-home",
    heading: "A place of our own",
    body: "Our first home became a collection of small rituals, shared plans, and room for the future.",
    imageId: "story-first-home",
    imageSlot: "storyLandscape",
    alt: "A photograph from the couple's first home",
    caption: "Our first home, and the beginning of so many shared routines.",
    order: 4,
  },
  {
    id: "raising-lenny",
    heading: "Raising Lenny",
    body: "Raising our dog together has been one of our favorite chapters yet.",
    imageId: "story-raising-lenny",
    imageSlot: "storyPortrait",
    alt: "The couple with their dog Lenny",
    caption: "Raising our dog together has been one of our favorite chapters yet.",
    order: 5,
  },
  {
    id: "beach-proposal",
    heading: "The question",
    body: "She said yes!",
    imageId: "story-beach-proposal",
    imageSlot: "storyPortrait",
    alt: "The couple together on a beach beside a lit marriage proposal display",
    caption: "A beachside question, answered with a joyful yes.",
    order: 6,
  },
  {
    id: "traditional-portrait",
    heading: "A celebration in red",
    body: " We marked our new chapter together in traditional Chinese wedding attire.",
    imageId: "story-traditional-portrait",
    imageSlot: "storyPortrait",
    alt: "The couple smiling together in traditional red wedding attire",
    caption: "A joyful portrait in traditional wedding attire.",
    order: 7,
  },
    {
    id: "courtyard-wedding",
    heading: "Walking into our next chapter",
    body: "We walk towards our new future hand in hand.",
    imageId: "story-garden-gate",
    imageSlot: "storyPortrait",
    alt: "The couple walking together through a traditional Chinese garden gate",
    caption: "A quiet walk through a place rich with history.",
    order: 8
    }
  // },
  // {
  //   id: "traditional-portrait",
  //   heading: "A celebration in red",
  //   body: "A joyful portrait in traditional wedding attire, marking a new chapter together.",
  //   imageId: "story-traditional-portrait",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple smiling together in traditional red wedding attire",
  //   caption: "A joyful portrait in traditional wedding attire.",
  //   order: 5,
  // },
  // {
  //   id: "garden-gate",
  //   heading: "A walk through history",
  //   body: "An unforgettable day together among the gardens and architecture of China.",
  //   imageId: "story-garden-gate",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple walking together through a traditional Chinese garden gate",
  //   caption: "A quiet walk through a place rich with history.",
  //   order: 6,
  // },

  // {
  //   id: "prom-rose",
  //   heading: "A high school memory",
  //   body: "A rose, a corsage, and one of the early memories that started it all.",
  //   imageId: "story-prom-rose",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple dressed up together, holding a pink rose",
  //   caption: "One of the early memories that started it all.",
  //   order: 9,
  // },
  // {
  //   id: "kayaking",
  //   heading: "Days on the water",
  //   body: "Exploring the lake together, one paddle at a time.",
  //   imageId: "story-kayaking",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple kayaking together on a lake",
  //   caption: "Exploring the lake together, one paddle at a time.",
  //   order: 10,
  // },
  // {
  //   id: "color-run",
  //   heading: "A colorful finish",
  //   body: "Running, laughing, and arriving home covered in color.",
  //   imageId: "story-color-run",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple smiling after a colorful fun run",
  //   caption: "Running, laughing, and arriving home covered in color.",
  //   order: 11,
  // },
  // {
  //   id: "school-hallway",
  //   heading: "Side by side",
  //   body: "Walking through the halls, with plenty of life still ahead of us.",
  //   imageId: "story-school-hallway",
  //   imageSlot: "storyLandscape",
  //   alt: "The couple walking hand in hand down a school hallway",
  //   caption: "Side by side, with plenty of life still ahead.",
  //   order: 12,
  // },
  // {
  //   id: "beach-proposal",
  //   heading: "The question",
  //   body: "A beachside question, answered with a joyful yes.",
  //   imageId: "story-beach-proposal",
  //   imageSlot: "storyPortrait",
  //   alt: "The couple together on a beach beside a lit marriage proposal display",
  //   caption: "A beachside question, answered with a joyful yes.",
  //   order: 13,
  // },
] satisfies StoryMoment[];
